name: "(vue-todo) Unit tests runner"

on:
  workflow_dispatch:
  push:
    paths:
      - 'vue-todo/**'
    branches:
      - main
  pull_request:
      paths:
      - 'vue-todo/**'

defaults:
  run:
    working-directory: vue-todo

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 19.4.0
          cache: 'npm'
          cache-dependency-path: 'vue-todo/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build --if-present
      - name: Run tests
        run: CI=true npm run test:unit
